// AUTO-GENERATED by per-section-migrate. Edit freely — Bob will treat this
// file as the canonical source for the "AboutTextSplit" section.

import React from 'react';
import Button from "@/components/ui/Button";
import TextAnimation from "@/components/ui/TextAnimation";
import { motion, useScroll, useTransform } from "motion/react";

export default function AboutTextSplitSection(): React.JSX.Element {
  const { scrollY } = useScroll();
  const opacity = useTransform(scrollY, [0, 150], [1, 0]);

  return (
    <div data-webild-section="AboutTextSplit"><section aria-label="About section" className=""><div className="flex flex-col mx-auto w-content-width"><div className="flex flex-col md:flex-row gap-3"><div className="w-full md:w-1/2"><TextAnimation text="A Legacy of Trust in Guanaja" variant="slide-up" gradientText={true} tag="h2" className="text-7xl 2xl:text-8xl leading-[1.15] font-semibold text-balance" /></div><div className="flex flex-col gap-2 w-full md:w-1/2"><motion.div style={{ opacity }}><TextAnimation key={0} text="For over 15 years, Powery & Asociados has been a trusted family-run company serving Guanaja and the Bay Islands. We provide essential products and services that support everyday life and development." variant="slide-up" gradientText={false} tag="p" className="text-xl md:text-2xl leading-snug text-balance" /></motion.div>
    <TextAnimation key={1} text="Our operations span two key areas. We supply high‑quality construction materials for builders and deliver reliable ice services that keep local businesses and families cool. Beyond that, we proudly support the local fishing community — providing the ice  that help sustain their daily work and preserve the region’s coastal heritage." variant="slide-up" gradientText={false} tag="p" className="text-xl md:text-2xl leading-snug text-balance" />
    <TextAnimation key={2} text="Additionally, Constructora Powery specializes in professional building, site planning, and land surveys. We bring technical expertise and a personal touch to every project." variant="slide-up" gradientText={false} tag="p" className="text-xl md:text-2xl leading-snug text-balance" />
    <TextAnimation key={3} text="At Powery & Asociados, we are more than a company. We are a family committed to strengthening our community, one project at a time." variant="slide-up" gradientText={false} tag="p" className="text-xl md:text-2xl leading-snug text-balance" /><div className="flex flex-wrap gap-3 mt-2 md:mt-3"><Button text="Home" href="/#services" variant="primary" /></div></div></div><div className="w-full border-b border-foreground/5" /></div></section></div>
  );
}
