// AUTO-GENERATED by per-section-migrate. Edit freely — Bob will treat this
// file as the canonical source for the "contact" section.

import React from 'react';
import ContactSplitForm from "@/components/sections/contact/ContactSplitForm";

export default function ContactSection(): React.JSX.Element {
  return (
    <div id="contact" data-section="contact">
      <ContactSplitForm
              tag="Get in Touch"
              title="Let's build something great together"
              description="Have a project in mind or need a quote for materials? Fill out the form below and our construction experts will get back to you shortly."
              inputs={[
                { name: "name", type: "text", placeholder: "Your Name", required: true },
                { name: "email", type: "email", placeholder: "Your Email", required: true },
                { name: "phone", type: "tel", placeholder: "Phone Number", required: false },
                { name: "company", type: "text", placeholder: "Company Name (Optional)", required: false }
              ]}
              textarea={{ name: "message", placeholder: "Tell us about your project or material needs...", rows: 5, required: true }}
              buttonText="Send Message"
              onSubmit={(data) => console.log("Form submitted:", data)} imageSrc=""
              textAnimation="fade-blur"
            />
    </div>
  );
}
