// AUTO-GENERATED by per-section-migrate. Edit freely — Bob will treat this
// file as the canonical source for the "faq" section.

import React from 'react';
import FaqSimple from "@/components/sections/faq/FaqSimple";

export default function FaqSection(): React.JSX.Element {
  return (
    <div id="faq" data-section="faq">
      <FaqSimple
              tag="Support"
              title="Frequently Asked Questions"
              description="Quick answers to common inquiries before you reach out."
              items={[
                { 
                  question: "How fast do you reply to quote requests?", 
                  answer: "We aim to respond to all inquiries and quote requests within 24 hours during regular business days." 
                },
                { 
                  question: "Do you deliver building materials to the site?", 
                  answer: "Yes, we offer delivery services for all our building materials directly to your construction site. Delivery fees may vary based on location and order size." 
                },
                { 
                  question: "Can I schedule a consultation for my project?", 
                  answer: "Absolutely. Once you submit the contact form, our team will reach out to schedule a consultation to discuss your project in detail." 
                },
                { 
                  question: "Do you handle both residential and commercial projects?", 
                  answer: "Yes, Constructora Powery has extensive experience managing and supplying materials for both residential homes and large-scale commercial developments." 
                }
              ]}
              textAnimation="slide-up"
            />
    </div>
  );
}
