// AUTO-GENERATED by per-section-migrate. Edit freely — Bob will treat this
// file as the canonical source for the "contact" section.

import React from 'react';
import ContactCta from '@/components/sections/contact/ContactCta';
import SectionErrorBoundary from "@/components/ui/SectionErrorBoundary";

export default function ContactSection(): React.JSX.Element {
  return (
    <div id="contact" data-section="contact">
        <SectionErrorBoundary name="contact">
              <ContactCta
        tag="Ready to build?"
        text="Start your next project with Guanaja's most trusted partner. Get your material estimate or book your construction consultation today."
        primaryButton={{
            text: "Start Now",
            href: "/contact",
          }}
        secondaryButton={{"href":"tel:+50495070946","text":"Call +504 95070946"}}
        textAnimation="slide-up"
      />
        </SectionErrorBoundary>
      </div>
  );
}
