// AUTO-GENERATED by per-section-migrate. Edit freely — Bob will treat this
// file as the canonical source for the "faq" section.

import React from 'react';
import FaqTabbedAccordion from '@/components/sections/faq/FaqTabbedAccordion';
import SectionErrorBoundary from "@/components/ui/SectionErrorBoundary";

export default function FaqSection(): React.JSX.Element {
  return (
    <div id="faq" data-section="faq">
        <SectionErrorBoundary name="faq">
              <FaqTabbedAccordion
          tag="Support"
          title="Common Questions"
          description="Get quick answers about material availability, delivery, and services."
          categories={[
            {
              name: "General",
              items: [
                {
                  question: "Do you deliver island-wide?",
                  answer: "Yes, our logistics fleet services the entire island daily.",
                },
                {
                  question: "Can I order materials online?",
                  answer: "Use our request portal for quotes and inventory availability.",
                },
              ],
            },
            {
              name: "Construction",
              items: [
                {
                  question: "How do I book a consultation?",
                  answer: "Select the Consultation service on our site to schedule a visit.",
                },
                {
                  question: "Do you offer construction timelines?",
                  answer: "We provide detailed scheduling and status tracking for all projects.",
                },
              ],
            },
          ]}
          textAnimation="fade"
        />
        </SectionErrorBoundary>
      </div>
  );
}
