// AUTO-GENERATED by per-section-migrate. Edit freely — Bob will treat this
// file as the canonical source for the "hero" section.

import React from 'react';
import HeroOverlay from '@/components/sections/hero/HeroOverlay';
import SectionErrorBoundary from "@/components/ui/SectionErrorBoundary";

export default function HeroSection(): React.JSX.Element {
  return (
    <div id="hero" data-section="hero">
        <SectionErrorBoundary name="hero">
              <HeroOverlay
          tag="Guanaja's Trusted Supplier"
          title="Powery & Asociados "
          description="Supplying the island with top-quality wood, concrete, roofing, and daily essentials while offering expert residential construction services to build your home from the ground up—reliable, locally stocked, and built for the island climate."
          primaryButton={{
            text: "Request a Quote",
            href: "#contact",
          }}
          secondaryButton={{
            text: "View Materials",
            href: "#materials",
          }}
          imageSrc="http://img.b2bpic.net/free-photo/tools-clay-work-sculpting_23-2149986247.jpg?_wi=1"
          textAnimation="fade-blur"
        />
        </SectionErrorBoundary>
      </div>
  );
}
