/* eslint-disable */
// @ts-nocheck — generated by catalog-eject; runtime-correct but TS strict-mode false-positives on inlined catalog body
import Button from "@/components/ui/Button";
import TextAnimation from "@/components/ui/TextAnimation";
import ImageOrVideo from "@/components/ui/ImageOrVideo";
import ScrollReveal from "@/components/ui/ScrollReveal";
import { cls } from "@/lib/utils";

const items = [
  {
    title: "Premium Lumber",
    description: "Treated wood for lasting structures.",
    imageSrc: "http://img.b2bpic.net/free-photo/brown-closeup-wooden-texture-macro_1122-1778.jpg",
    bullets: ["Pine Wood", "Marine PlayWood", "PlayWood", "Panelit", "Framing Lumber"]
  },
  {
    title: "Concrete & Aggregates",
    description: "Sand, gravel, and high-strength concrete.",
    imageSrc: "https://storage.googleapis.com/webild/users/user_3FvS6fUSGcZ0ltOmklw1moE7HZg/uploaded-1784645129490-cx7jmuje.avif",
    bullets: ["Portland Cement", "Fine Sand", "Coarse Gravel", "Ready-Mix Bags", "Concrete Blocks"]
  },
  {
    title: "Roofing Systems",
    description: "Weather-resistant, durable roofing solutions.",
    imageSrc: "http://img.b2bpic.net/free-photo/modern-new-painted-metal-surface_23-2148394678.jpg",
    bullets: ["Corrugated Metal, Pvc, Pvc", "Asphalt Shingles", "Roofing Felt", "Flashing & Trim", "Roof Sealants"]
  },
  {
    title: "Hardware Tools",
    description: "Every tool you need for the job.",
    imageSrc: "http://img.b2bpic.net/free-photo/workshop-with-different-implements_23-2148180525.jpg",
    bullets: ["Power Drills", "Hand Saws", "Hammers & Mallets", "Measuring Tapes", "Wrenches & Pliers"]
  },
  {
    title: "Construction Services",
    description: "Full-cycle build and management.",
    imageSrc: "http://img.b2bpic.net/free-photo/full-shot-roofers-working-together-with-helmets_23-2149343707.jpg",
    bullets: ["Project Planning", "Site Preparation", "Foundation Work", "Framing & Roofing", "Finishing Touches"]
  },
  {
    title: "Paints & Sealants",
    description: "Island-grade weather protection.",
    imageSrc: "http://img.b2bpic.net/free-photo/old-fence-s-renovaiting-process-by-worker-he-apply-brown-paint-with-brush-wearing-protective-gloves_613910-17110.jpg",
    bullets: ["Exterior Paint", "Interior Primer", "Waterproofing", "Wood Stains", "Caulking Tubes"]
  },
  {
    title: "Daily Essentials",
    description: "Including ice and basic supplies.",
    imageSrc: "https://storage.googleapis.com/webild/users/user_3FvS6fUSGcZ0ltOmklw1moE7HZg/uploaded-1784734769532-5mmjw7g8.jpg",
    bullets: ["Ice & Cold Storage Packs", "Drinking Water & Beverage", "Snacks & Packaged Food", "Cleaning Products & Detergents", "Basic Household Goods"]
  },
  {
    title: "Marine Supply",
    description: "Quality gear for marine construction and maintenance.",
    imageSrc: "https://storage.googleapis.com/webild/users/user_3FvS6fUSGcZ0ltOmklw1moE7HZg/uploaded-1784729440252-hp39wszy.jpg",
    bullets: ["Boat Pumps (Bilge & Freshwater)", "Stainless Fasteners", "Boat Paint", "Dock Cleats", "Mooring Lines"]
  }
];

type FeatureItem = {
  title: string;
  description: string;
  href?: string;
} & ({ imageSrc: string; videoSrc?: never } | { videoSrc: string; imageSrc?: never });

interface FeaturesImageBentoProps {
  tag: string;
  title: string;
  description: string;
  primaryButton?: { text: string; href: string };
  secondaryButton?: { text: string; href: string };
  items: FeatureItem[];
  textAnimation: "slide-up" | "fade-blur" | "fade";
}

const MaterialsInline = () => {
  const gridClasses = [
    "md:col-span-2",
    "md:col-span-4",
    "md:col-span-3",
    "md:col-span-3",
    "md:col-span-3",
    "md:col-span-3",
    "md:col-span-3",
    "md:col-span-3",
  ];

  const staggerDelays = [
    0,
    0.1,
    0,
    0.1,
    0,
    0.1,
    0,
    0.1,
  ];

  return (
    <section aria-label="Features image bento section" className="py-20">
      <div className="flex flex-col gap-8 md:gap-10">
        <div className="flex flex-col items-center w-content-width mx-auto gap-4 bg-white text-black p-8 md:p-12 rounded-3xl">
          <div className="px-3 py-1 mb-1 text-sm card rounded w-fit">
            <p>{"Our Inventory"}</p>
          </div>

          <TextAnimation
            text={"All-in-One Material Showcase"}
            variant={"slide-up"}
            gradientText={false}
            tag="h2"
            className="md:max-w-8/10 text-6xl 2xl:text-7xl leading-[1.15] font-semibold text-center text-balance"
          />

          <TextAnimation
            text={"From foundation materials to daily essentials, we maintain a comprehensive, island-ready inventory."}
            variant={"slide-up"}
            gradientText={false}
            tag="p"
            className="md:max-w-7/10 text-lg md:text-xl leading-snug text-center text-balance text-black/80"
          />

          {(undefined || undefined) && (
            <div className="flex flex-wrap justify-center gap-3 mt-2 md:mt-3">
              {undefined && <Button text={undefined.text} href={undefined.href} variant="primary"/>}
              {undefined && <Button text={undefined.text} href={undefined.href} variant="secondary" animationDelay={0.1} />}
            </div>
          )}
        </div>

        <div className="w-content-width mx-auto grid grid-cols-1 md:grid-cols-6 gap-3">
          {items.map((item, index) => {
            const content = (
              <div className="relative h-80 xl:h-100 2xl:h-120 overflow-hidden">
                <ImageOrVideo
                  imageSrc={item.imageSrc}
                  videoSrc={item.videoSrc}
                  className="rounded group-hover:scale-105 transition-transform duration-500"
                />

                <div className="absolute inset-x-5 bottom-5 xl:inset-x-6 xl:bottom-6 2xl:inset-x-7 2xl:bottom-7 flex flex-col text-background">
                  <span className="text-2xl font-semibold leading-snug truncate">{item.title}</span>
                  <span className="text-base leading-snug truncate">{item.description}</span>
                  {item.bullets && item.bullets.length > 0 && (
                    <div className="flex flex-col mt-2 space-y-0.5">
                      {item.bullets.map((bullet, i) => (
                        <span key={i} className="text-sm opacity-90 truncate">{i === 0 ? bullet : `• ${bullet}`}</span>
                      ))}
                    </div>
                  )}
                </div>
              </div>
            );

            return (
              <ScrollReveal key={index} variant="slide-up" delay={staggerDelays[index]} className={cls("col-span-1 group", gridClasses[index])}>
                {item.href ? (
                  <a href={item.href} className="block overflow-hidden rounded">
                    {content}
                  </a>
                ) : (
                  <div className="overflow-hidden rounded">
                    {content}
                  </div>
                )}
              </ScrollReveal>
            );
          })}
        </div>
      </div>
    </section>
  );
};

export default function MaterialsSection() {
  return (
    <div data-webild-section="materials" data-section="materials" id="materials">
      <MaterialsInline />
    </div>
  );
}
