// AUTO-GENERATED by per-section-migrate. Edit freely — Bob will treat this
// file as the canonical source for the "metrics" section.

import React from 'react';
import MetricsIconCards from '@/components/sections/metrics/MetricsIconCards';
import { Truck, Users, Wrench } from "lucide-react";
import SectionErrorBoundary from "@/components/ui/SectionErrorBoundary";

export default function MetricsSection(): React.JSX.Element {
  return (
    <div id="metrics" data-section="metrics">
        <SectionErrorBoundary name="metrics">
              <MetricsIconCards
          tag="Our Impact"
          title="Serving Guanaja Daily"
          description="Proven results for island construction and supply needs."
          metrics={[
            {
              icon: Wrench,
              title: "Successful Builds",
              value: "15+",
            },
            {
              icon: Truck,
              title: "Deliveries Completed",
              value: "10k+",
            },
            {
              icon: Users,
              title: "Local Clients",
              value: "15+",
            },
          ]}
          textAnimation="slide-up"
        />
        </SectionErrorBoundary>
      </div>
  );
}
