// AUTO-GENERATED by per-section-migrate. Edit freely — Bob will treat this
// file as the canonical source for the "services" section.

import React from 'react';
import PricingMediaCards from '@/components/sections/pricing/PricingMediaCards';
import SectionErrorBoundary from "@/components/ui/SectionErrorBoundary";

export default function ServicesSection(): React.JSX.Element {
  return (
    <div id="services" data-section="services">
        <SectionErrorBoundary name="services">
              <PricingMediaCards
          tag="Services"
          title="Construction & Delivery"
          description="Professional services tailored for Guanaja residents."
          plans={[
            {
              tag: "Expert",
              price: "Consultation",
              period: "Book Now",
              features: [
                "Site assessment",
                "Material estimation",
                "Structural planning",
              ],
              primaryButton: {
                text: "Book Session",
                href: "#contact",
              },
              imageSrc: "http://img.b2bpic.net/free-photo/architects-looking-plan-front-house_23-2147813107.jpg",
            },
            {
              tag: "Fast",
              price: "Bulk Delivery",
              period: "Daily",
              features: [
                "Sand & Gravel",
                "Full Lumber loads",
                "Priority scheduling",
              ],
              primaryButton: {
                text: "Request Delivery",
                href: "#contact",
              },
              imageSrc: "http://img.b2bpic.net/free-photo/waibaidu-bridge-shanghai_1359-928.jpg",
            },
          ]}
          textAnimation="fade"
        />
        </SectionErrorBoundary>
      </div>
  );
}
