/* eslint-disable */
// @ts-nocheck — generated by catalog-eject; runtime-correct but TS strict-mode false-positives on inlined catalog body
import { Check } from "lucide-react";
import Button from "@/components/ui/Button";
import TextAnimation from "@/components/ui/TextAnimation";
import ImageOrVideo from "@/components/ui/ImageOrVideo";
import ScrollReveal from "@/components/ui/ScrollReveal";
import Carousel from "@/components/ui/Carousel";

const plans = [
  {
    tag: "Expert",
    price: "Consultation",
    period: "Book Now",
    features: [
      "Site assessment",
      "Material estimation",
      "Structural planning"
    ],
    primaryButton: {
      text: "Book Session",
      href: "#contact"
    },
    images: [
      "http://img.b2bpic.net/free-photo/architects-looking-plan-front-house_23-2147813107.jpg",
      "https://images.unsplash.com/photo-1503387762-592deb58ef4e?q=80&w=2831&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1541888086425-d81bb19240f5?q=80&w=2940&auto=format&fit=crop"
    ]
  },
  {
    tag: "Fast",
    price: "Bulk Delivery",
    period: "Daily",
    features: [
      "Sand & Gravel",
      "Full Lumber loads",
      "Priority scheduling"
    ],
    primaryButton: {
      text: "Request Delivery",
      href: "#contact"
    },
    images: [
      "https://storage.googleapis.com/webild/users/user_3FvS6fUSGcZ0ltOmklw1moE7HZg/uploaded-1784570477719-drirzw43.jpg",
      "https://storage.googleapis.com/webild/users/user_3FvS6fUSGcZ0ltOmklw1moE7HZg/uploaded-1784570552287-d1vb9obf.jpg",
      "https://storage.googleapis.com/webild/users/user_3FvS6fUSGcZ0ltOmklw1moE7HZg/uploaded-1784570590381-24ab9aw3.jpg"
    ]
  }
];

type PricingPlan = {
  tag: string;
  price: string;
  period: string;
  features: string[];
  primaryButton: { text: string; href: string };
} & ({ imageSrc: string; videoSrc?: never } | { videoSrc: string; imageSrc?: never });

const ServicesInline = () => (
  <section aria-label="Pricing section" className="py-20">
    <div className="flex flex-col gap-8 md:gap-10">
      <div className="flex flex-col items-center gap-2 w-content-width mx-auto">
        <div className="px-3 py-1 mb-1 text-sm card rounded w-fit">
          <p>{"Services"}</p>
        </div>

        <TextAnimation
          text={"Construction & Delivery"}
          variant={"fade"}
          gradientText={true}
          tag="h2"
          className="md:max-w-8/10 text-6xl 2xl:text-7xl leading-[1.15] font-semibold text-center text-balance"
        />

        <TextAnimation
          text={"Professional services tailored for Guanaja residents."}
          variant={"fade"}
          gradientText={false}
          tag="p"
          className="md:max-w-7/10 text-lg md:text-xl leading-snug text-center text-balance"
        />

        {(undefined || undefined) && (
          <div className="flex flex-wrap justify-center gap-3 mt-2 md:mt-3">
            {undefined && <Button text={undefined.text} href={undefined.href} variant="primary"/>}
            {undefined && <Button text={undefined.text} href={undefined.href} variant="secondary"animationDelay={0.1} />}
          </div>
        )}
      </div>

      <div className="flex flex-col gap-5 w-content-width mx-auto">
        {plans.map((plan) => (
          <ScrollReveal
            variant="fade-blur"
            key={plan.tag}
            className="flex flex-col md:flex-row gap-6 md:gap-10 p-6 md:p-10 card rounded"
          >
            <div className="w-full md:w-1/2 aspect-square md:aspect-4/3 rounded overflow-hidden">
              {plan.images ? (
                <Carousel className="w-full h-full" itemClassName="w-full h-full">
                  {plan.images.map((src, idx) => (
                    <ImageOrVideo key={idx} imageSrc={src} className="w-full h-full object-cover" />
                  ))}
                </Carousel>
              ) : (
                <ImageOrVideo imageSrc={plan.imageSrc} videoSrc={plan.videoSrc} className="w-full h-full object-cover" />
              )}
            </div>

            <div className="flex flex-col justify-center gap-2 w-full md:w-1/2">
              <div className="px-3 py-1 mb-1 w-fit text-sm card rounded">
                <p>{plan.price}{plan.period}</p>
              </div>
              <h3 className="text-4xl md:text-5xl font-semibold leading-[1.15] text-balance">{plan.tag}</h3>

              <div className="flex flex-col gap-3 mt-1">
                {plan.features.map((feature) => (
                  <div key={feature} className="flex items-start gap-3">
                    <div className="flex items-center justify-center shrink-0 size-6 primary-button rounded">
                      <Check className="size-3 text-primary-cta-text" strokeWidth={2} />
                    </div>
                    <span className="text-base leading-snug">{feature}</span>
                  </div>
                ))}
              </div>

              <Button text={plan.primaryButton.text} href={plan.primaryButton.href} variant="primary" className="w-fit mt-2 md:mt-3" />
            </div>
          </ScrollReveal>
        ))}
      </div>
    </div>
  </section>
);

export default function ServicesSection() {
  return (
    <div data-webild-section="services" data-section="services" id="services">
      <ServicesInline />
    </div>
  );
}
