// AUTO-GENERATED by per-section-migrate. Edit freely — Bob will treat this
// file as the canonical source for the "testimonials" section.

import React from 'react';
import TestimonialMarqueeOverlayCards from '@/components/sections/testimonial/TestimonialMarqueeOverlayCards';
import SectionErrorBoundary from "@/components/ui/SectionErrorBoundary";

export default function TestimonialsSection(): React.JSX.Element {
  return (
    <div id="testimonials" data-section="testimonials">
        <SectionErrorBoundary name="testimonials">
              <TestimonialMarqueeOverlayCards
          tag="Voices"
          title="Trusted by Island Residents"
          description="Hear how we help build and supply the island."
          testimonials={[
            {
              name: "Dunbar Rock ",
              role: "Hotel",
              company: "Eco‑tourism and hospitality business",
              rating: 5,
              imageSrc: "https://storage.googleapis.com/webild/users/user_3FvS6fUSGcZ0ltOmklw1moE7HZg/uploaded-1784656555315-5yajanq0.webp",
            },
            {
              name: "Hotel Guanaja del Este",
              role: "Business",
              company: "Eco‑style hotel",
              rating: 5,
              imageSrc: "https://storage.googleapis.com/webild/users/user_3FvS6fUSGcZ0ltOmklw1moE7HZg/uploaded-1784656710399-ykz6lgow.webp",
            },
            {
              name: "Jake Ebanks",
              role: "Architect",
              company: "Floor Plans & 3D Designs",
              rating: 5,
              imageSrc: "https://storage.googleapis.com/webild/users/user_3FvS6fUSGcZ0ltOmklw1moE7HZg/uploaded-1784654034539-24t2owe5.jpg",
            },
            {
              name: "Fly Fish guanaja",
              role: "Company",
              company: "Eco‑tourism and hospitality business",
              rating: 5,
              imageSrc: "https://storage.googleapis.com/webild/users/user_3FvS6fUSGcZ0ltOmklw1moE7HZg/uploaded-1784656382248-xcpikcez.webp",
            },
            {
              name: "Clarks cay",
              role: "Business",
              company: "Boutique private island resort",
              rating: 5,
              imageSrc: "https://storage.googleapis.com/webild/users/user_3FvS6fUSGcZ0ltOmklw1moE7HZg/uploaded-1784656894307-18nismk1.jpg",
            },
          ]}
          textAnimation="fade-blur"
        />
        </SectionErrorBoundary>
      </div>
  );
}
