// AUTO-GENERATED by per-section-migrate. Edit freely — Bob will treat this
// file as the canonical source for the "testimonials" section.

import React from 'react';
import TestimonialMarqueeOverlayCards from '@/components/sections/testimonial/TestimonialMarqueeOverlayCards';
import SectionErrorBoundary from "@/components/ui/SectionErrorBoundary";

export default function TestimonialsSection(): React.JSX.Element {
  return (
    <div id="testimonials" data-section="testimonials">
        <SectionErrorBoundary name="testimonials">
              <TestimonialMarqueeOverlayCards
          tag="Voices"
          title="Trusted by Island Residents"
          description="Hear how we help build and supply the island."
          testimonials={[
            {
              name: "Dunbar Rock ",
              role: "Hotel",
              company: "Eco‑tourism and hospitality business",
              rating: 5,
              imageSrc: "http://img.b2bpic.net/free-photo/portrait-smiling-male-carpenter-leaning-workbench_23-2147944946.jpg",
            },
            {
              name: "David M.",
              role: "Homeowner",
              company: "West End",
              rating: 5,
              imageSrc: "http://img.b2bpic.net/free-photo/architect-smiling-safety-equipment_23-2148242954.jpg",
            },
            {
              name: "Jake Ebanks",
              role: "Architect",
              company: "Floor Plans & 3D Designs",
              rating: 5,
              imageSrc: "https://storage.googleapis.com/webild/users/user_3FvS6fUSGcZ0ltOmklw1moE7HZg/uploaded-1784654034539-24t2owe5.jpg",
            },
            {
              name: "Fly Fish guanaja",
              role: "Company",
              company: "Eco‑tourism and hospitality business",
              rating: 5,
              imageSrc: "https://storage.googleapis.com/webild/users/user_3FvS6fUSGcZ0ltOmklw1moE7HZg/uploaded-1784656382248-xcpikcez.webp",
            },
            {
              name: "Julia P.",
              role: "Homeowner",
              company: "Sandy Bay",
              rating: 5,
              imageSrc: "http://img.b2bpic.net/free-photo/nature-landscape-hawaii-with-digital-art-style_23-2151793616.jpg",
            },
          ]}
          textAnimation="fade-blur"
        />
        </SectionErrorBoundary>
      </div>
  );
}
